version: '3.8'

services:
  backend:
    image: docker.io/naglissul/bankas-skafis-api:latest
    pull_policy: always
    ports:
      - '9000:9000'
    environment:
      - FIREBASE_SERVICE_ACCOUNT_PATH=/etc/secrets/firebase-admin.json
      - ENVIRONMENT=dev
      - PORT=9000
    volumes:
      - ${SDK_LOCAL_PATH}:/etc/secrets/firebase-admin.json
